# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
        app: web-ui
        tier: frontend
  template:
    metadata:
      labels:
        app: web-ui
        tier: frontend
    spec:
      containers:
      - name: react-web-ui
        image: "web-ui:prod"
        env:
        - name: GET_HOSTS_FROM
          value: "dns"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80